import type { Metadata } from "next";
import Nav from "../../../components/Nav";
import Footer from "../../../components/Footer";
import { FileText, Sparkles } from "lucide-react";
import { getTranslations } from "next-intl/server";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getTranslations("terms");
  return {
    title: t("metaTitle", { defaultValue: "Terms of Service" }),
    description: t("metaDescription", { defaultValue: "CueQuote terms of service — the rules and guidelines for using our platform." }),
    alternates: { canonical: "/terms" },
  };
}

const SECTIONS = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `By accessing or using CueQuote ("the Service"), you agree to be bound by these Terms of Service. If you are using CueQuote on behalf of an organization, you represent that you have authority to bind that organization to these terms.`,
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: `CueQuote is a software-as-a-service platform that helps AV production companies, event agencies, and freelance technicians generate professional equipment proposals using AI. The Service includes proposal generation, equipment catalog management, PDF export, client sharing, and related features.`,
  },
  {
    id: "accounts",
    title: "3. Accounts",
    content: `You must create an account to use CueQuote. You are responsible for maintaining the security of your account credentials and for all activity under your account. You must provide accurate and complete information during registration and keep it up to date.`,
  },
  {
    id: "billing",
    title: "4. Subscriptions & Billing",
    content: `CueQuote offers free and paid plans. Paid subscriptions are billed monthly or annually via Stripe. You may cancel at any time — cancellation takes effect at the end of the current billing period. Refunds are not provided for partial billing periods. We reserve the right to change pricing with 30 days notice.`,
  },
  {
    id: "your-data",
    title: "5. Your Data",
    content: `You retain all rights to the data you input into CueQuote, including event descriptions, client information, equipment catalogs, and generated proposals. We do not claim ownership of your content. You grant us a limited license to process your data solely to provide the Service.`,
  },
  {
    id: "ai-content",
    title: "6. AI-Generated Content",
    content: `Proposals generated by CueQuote's AI are provided as suggestions. You are responsible for reviewing, editing, and verifying all AI-generated content before sharing with clients. CueQuote does not guarantee the accuracy, completeness, or suitability of AI-generated proposals for any specific event.`,
  },
  {
    id: "acceptable-use",
    title: "7. Acceptable Use",
    content: `You agree not to: use CueQuote for any unlawful purpose; attempt to gain unauthorized access to the Service; interfere with the operation of the Service; resell or redistribute the Service without authorization; or use automated tools to scrape or extract data from the Service.`,
  },
  {
    id: "availability",
    title: "8. Availability & Support",
    content: `We aim to maintain high availability but do not guarantee uninterrupted access. We may perform maintenance that temporarily affects availability. Support is provided via email during business hours (CET). Response times depend on your subscription plan.`,
  },
  {
    id: "liability",
    title: "9. Limitation of Liability",
    content: `To the maximum extent permitted by law, CueQuote and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.`,
  },
  {
    id: "termination",
    title: "10. Termination",
    content: `We may suspend or terminate your account if you violate these terms. You may delete your account at any time through the Settings page. Upon termination, your data will be deleted in accordance with our Privacy Policy.`,
  },
  {
    id: "changes",
    title: "11. Changes to Terms",
    content: `We may modify these terms at any time. Material changes will be communicated via email or in-app notification at least 14 days before taking effect. Continued use of CueQuote after changes constitutes acceptance.`,
  },
  {
    id: "governing-law",
    title: "12. Governing Law",
    content: `These terms are governed by the laws of the European Union and the applicable member state where AVE Events is established. Any disputes shall be resolved in the courts of that jurisdiction.`,
  },
  {
    id: "contact",
    title: "13. Contact",
    content: `For questions about these terms, contact us at legal@cuequote.com.`,
  },
];

export default function TermsPage() {
  return (
    <>
      <Nav />

      {/* Hero */}
      <section style={{
        padding: "100px 24px 60px",
        background: "linear-gradient(180deg, #f0fdf4 0%, #fff 100%)",
        textAlign: "center",
      }}>
        <div style={{ maxWidth: 720, margin: "0 auto" }}>
          <div style={{
            display: "inline-flex", alignItems: "center", gap: 6, fontSize: 13, fontWeight: 600, color: "#10b981",
            background: "#ecfdf5", border: "1px solid rgba(16,185,129,0.15)", padding: "6px 14px", borderRadius: 20, marginBottom: 20,
          }}>
            <FileText size={14} /> Terms of Service
          </div>
          <h1 style={{
            fontFamily: "var(--font-dm-sans)", fontWeight: 800, fontSize: 44, color: "#08172E",
            marginBottom: 12, lineHeight: 1.15, letterSpacing: -1,
          }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 17, color: "#6b7280", marginBottom: 8, lineHeight: 1.7 }}>
            The rules and guidelines for using CueQuote.
          </p>
          <p style={{ fontSize: 14, color: "#9ca3af" }}>
            Last updated: March 16, 2026
          </p>
        </div>
      </section>

      {/* Table of Contents + Content */}
      <section style={{ padding: "64px 24px 96px" }}>
        <div style={{ maxWidth: 860, margin: "0 auto" }} className="terms-layout">
          <style>{`
            .terms-layout { display: grid; grid-template-columns: 220px 1fr; gap: 48px; }
            @media (max-width: 768px) {
              .terms-layout { grid-template-columns: 1fr !important; gap: 32px !important; }
            }
          `}</style>

          {/* Table of Contents */}
          <aside>
            <div style={{
              position: "sticky", top: 88,
              background: "#f9fafb", borderRadius: 16, padding: "24px 20px",
              border: "1px solid #e5e7eb",
            }}>
              <h3 style={{
                fontFamily: "var(--font-dm-sans)", fontWeight: 700, fontSize: 13, color: "#08172E",
                textTransform: "uppercase", letterSpacing: 1, marginBottom: 16,
              }}>
                Contents
              </h3>
              <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                {SECTIONS.map((s) => (
                  <a key={s.id} href={`#${s.id}`} style={{
                    textDecoration: "none", fontSize: 13, color: "#6b7280",
                    lineHeight: 1.4, transition: "color 0.2s",
                  }}>
                    {s.title}
                  </a>
                ))}
              </div>
            </div>
          </aside>

          {/* Sections */}
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            {SECTIONS.map((s, i) => (
              <div key={s.id} id={s.id} style={{
                padding: "32px 0",
                borderBottom: i < SECTIONS.length - 1 ? "1px solid #e5e7eb" : "none",
              }}>
                <h2 style={{
                  fontFamily: "var(--font-dm-sans)", fontWeight: 700, fontSize: 22, color: "#08172E",
                  marginBottom: 16,
                }}>
                  {s.title}
                </h2>
                <p style={{ fontSize: 16, color: "#4b5563", lineHeight: 1.8 }}>
                  {s.content}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact banner */}
      <section style={{
        padding: "64px 24px",
        background: "#08172E",
        textAlign: "center",
      }}>
        <div style={{ maxWidth: 520, margin: "0 auto" }}>
          <h2 style={{
            fontFamily: "var(--font-dm-sans)", fontWeight: 800, fontSize: 28, color: "#fff",
            marginBottom: 12, lineHeight: 1.3,
          }}>
            Questions about our terms?
          </h2>
          <p style={{ fontSize: 16, color: "#94a3b8", marginBottom: 24, lineHeight: 1.6 }}>
            Our team is here to help clarify anything.
          </p>
          <a
            href="mailto:legal@cuequote.com"
            style={{
              display: "inline-block", background: "#10b981", color: "#fff",
              padding: "14px 32px", borderRadius: 10, fontWeight: 600, fontSize: 16,
              textDecoration: "none",
            }}
          >
            Contact Legal Team
          </a>
        </div>
      </section>

      <Footer />
    </>
  );
}
